//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vneed.UI.Web.Page {
    
    
    public partial class index {
        
        /// <summary>
        /// ShowAreaWebUserControl11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vneed.UI.Web.WebUserControl.ShowAreaWebUserControl1 ShowAreaWebUserControl11;
        
        /// <summary>
        /// CatalogList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vneed.UI.Web.WebUserControl.CatalogList CatalogList1;
        
        /// <summary>
        /// RecommendedItemList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vneed.UI.Web.WebUserControl.RecommendedItemList RecommendedItemList1;
    }
}
