//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vneed.UI.Web.Page.V2 {
    
    
    public partial class index {
        
        /// <summary>
        /// ProductImageShow1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vneed.UI.Web.WebUserControl.V2.ProductImageShow ProductImageShow1;
    }
}
