//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vneed.UI.Web.Page.V2 {
    
    
    public partial class index {
        
        /// <summary>
        /// ProductImageShowControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vneed.UI.Web.WebUserControl.V2.ProductImageShow ProductImageShowControl1;
        
        /// <summary>
        /// CatalogListControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vneed.UI.Web.WebUserControl.V2.CatalogListControl CatalogListControl1;
        
        /// <summary>
        /// BestSellerItemListControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vneed.UI.Web.WebUserControl.V2.BestSellerItemListControl BestSellerItemListControl1;
        
        /// <summary>
        /// RecommendedItemListControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vneed.UI.Web.WebUserControl.V2.RecommendedItemListControl RecommendedItemListControl1;
    }
}
